### ISSUE TITLE
[P1] Unit test with hand-crafted models

### ISSUE THREAD

**Issue by frankaging** [frankaging/align-transformers#19]
Description:
Currently, we don't have a systematic way of unit testing the library. A good way is just to create some hand-crafted models (i.e., with fixed weights), do interventions, and check counterfactual behaviors.

Probably not hand-crafted transformers, but just simple MLPs with 3 hidden states, for instance.

**Comment by aryamanarora** [comment]
For a decoder-only causal LM we can also do tests to check that e.g. intervention on a module at position $p$ doesn't affect hidden states at position $< p$.

**Comment by frankaging** [comment]
closing this ticket as the initial work is done. will open new tickets for new tests. considering one ticket to track many tests now. 

in the future, each PR should also consider to include new test cases.
