### ISSUE TITLE
LlamaForCausalLM (case sensitive issue?)

### ISSUE THREAD

**Issue by SungMinCho** [frankaging/align-transformers#3]
https://github.com/frankaging/align-transformers/blob/6f2b7d7ad8203d263cd20b6da7a6be6171d1e690/models/modelings_alignable.py#LL11C2-L11C2

Could you maybe add `"LlamaForCausalLM"` here? (It's not captured by `"LLaMAForCausalLM"`)

My alpaca weights recovered as guided in https://github.com/tatsu-lab/stanford_alpaca has the following config for some reason:

```
LlamaConfig {
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.29.2",
  "use_cache": true,
  "vocab_size": 32001
}
```

BTW, thanks for this awesome project!

**Comment by frankaging** [comment]
Thanks for the comments! 

I can definitely make the change. But do you want to make this change with a pull request on this? I can merge this to the main branch for you. 

Thanks.

**Comment by SungMinCho** [comment]
Thanks for the reply! I've created a small PR :)
